src/Entity/CarnetSante.php
<?php

namespace App\Entity;

use App\Repository\CarnetSanteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CarnetSanteRepository::class)
 */
class CarnetSante
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToMany(targetEntity=VisiteMedical::class, mappedBy="carnet", cascade={"persist", "remove"})
     */
    private $visiteMedicals;

    /**
     * @ORM\OneToOne(targetEntity=Animal::class, inversedBy="carnetSante", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $animal;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="carnetSantes")
     */
    private $user;

    /**
     * @ORM\OneToOne(targetEntity=QrCode::class, mappedBy="carnet", cascade={"persist", "remove"})
     */
    private $qrCode;

    public function __construct()
    {
        $this->visiteMedicals = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection|VisiteMedical[]
     */
    public function getVisiteMedicals(): Collection
    {
        return $this->visiteMedicals;
    }

    public function addVisiteMedical(VisiteMedical $visiteMedical): self
    {
        if (!$this->visiteMedicals->contains($visiteMedical)) {
            $this->visiteMedicals[] = $visiteMedical;
            $visiteMedical->setCarnet($this);
        }

        return $this;
    }

    public function removeVisiteMedical(VisiteMedical $visiteMedical): self
    {
        if ($this->visiteMedicals->removeElement($visiteMedical)) {
            // set the owning side to null (unless already changed)
            if ($visiteMedical->getCarnet() === $this) {
                $visiteMedical->setCarnet(null);
            }
        }

        return $this;
    }

    public function getAnimal(): ?Animal
    {
        return $this->animal;
    }

    public function setAnimal(Animal $animal): self
    {
        $this->animal = $animal;

        return $this;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getQrCode(): ?QrCode
    {
        return $this->qrCode;
    }

    public function setQrCode(?QrCode $qrCode): self
    {
        // unset the owning side of the relation if necessary
        if ($qrCode === null && $this->qrCode !== null) {
            $this->qrCode->setCarnet(null);
        }

        // set the owning side of the relation if necessary
        if ($qrCode !== null && $qrCode->getCarnet() !== $this) {
            $qrCode->setCarnet($this);
        }

        $this->qrCode = $qrCode;

        return $this;
    }
}

src/Entity/VisiteMedical.php
<?php

namespace App\Entity;

use App\Repository\VisiteMedicalRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VisiteMedicalRepository::class)
 */
class VisiteMedical
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date_visite;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $symptome;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $diagnostique;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $analyses;

    /**
     * @ORM\ManyToOne(targetEntity=Specialiste::class,)
     * @ORM\JoinColumn(nullable=true)
     */
    private $specialiste;

    /**
     * @ORM\ManyToOne(targetEntity=CarnetSante::class, inversedBy="visiteMedicals")
     * @ORM\JoinColumn(nullable=false)
     */
    private $carnet;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $action;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateVisite(): ?\DateTimeInterface
    {
        return $this->date_visite;
    }

    public function setDateVisite(\DateTimeInterface $date_visite): self
    {
        $this->date_visite = $date_visite;

        return $this;
    }

    public function getSymptome(): ?string
    {
        return $this->symptome;
    }

    public function setSymptome(?string $symptome): self
    {
        $this->symptome = $symptome;

        return $this;
    }

    public function getDiagnostique(): ?string
    {
        return $this->diagnostique;
    }

    public function setDiagnostique(?string $diagnostique): self
    {
        $this->diagnostique = $diagnostique;

        return $this;
    }

    public function getAnalyses(): ?string
    {
        return $this->analyses;
    }

    public function setAnalyses(?string $analyses): self
    {
        $this->analyses = $analyses;

        return $this;
    }

    public function getSpecialiste(): ?Specialiste
    {
        return $this->specialiste;
    }

    public function setSpecialiste(Specialiste $specialiste): self
    {
        $this->specialiste = $specialiste;

        return $this;
    }

    public function getCarnet(): ?CarnetSante
    {
        return $this->carnet;
    }

    public function setCarnet(?CarnetSante $carnet): self
    {
        $this->carnet = $carnet;

        return $this;
    }

    public function getAction(): ?string
    {
        return $this->action;
    }

    public function setAction(string $action): self
    {
        $this->action = $action;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }
}

src/Form/CarnetSanteType.php
<?php

namespace App\Form;

use App\Entity\CarnetSante;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;

class CarnetSanteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('', Entity::class, [
                "class" => CarnetSante::class,

            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => CarnetSante::class,
        ]);
    }
}

src/Controller/CarnetSanteController.php
<?php

namespace App\Controller;

use App\Entity\Animal;
use App\Entity\QrCode;
use App\Entity\CarnetSante;
use App\Entity\VisiteMedical;
use App\Form\CarnetSanteType;
use App\Repository\QrCodeRepository;
use App\Repository\CarnetSanteRepository;
use App\Repository\VisiteMedicalRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\VaccinsEtOperationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/abonne/carnet')]
class CarnetSanteController extends AbstractController
{
    #[Route('/', name: 'carnet_sante_index', methods: ['GET'])]
    public function index(CarnetSanteRepository $carnetSanteRepository): Response
    {

        return $this->render('carnet_sante/index.html.twig', [
            'carnet_santes' => $carnetSanteRepository->findAll(),
        ]);
    }

    #[Route('/{id}', name: 'carnet_sante_show', methods: ['GET'])]
    public function show(CarnetSante $carnetSante, VisiteMedicalRepository $vr, Request $request, QrCodeRepository $qr,): Response
    {
        if (!$qr->aideqrcode($carnetSante->getId())) {
            $host = $request->getHttpHost();
            $suite = $request->getPathInfo();
            //dd($referer = $request->headers->get('referer'));
            $url = $host . $suite;
            $qrCode = new QrCode();
            $qrCode->setCarnet($carnetSante);
            $qrCode->setImageQrc("http://" . $url);

            //Creation du qrcode en bdd
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($qrCode);
            $entityManager->flush();
        }

        $visites = $vr->jointCarnetVisite($carnetSante->getId());
        return $this->render('carnet_sante/show.html.twig', [
            'carnet_sante' => $carnetSante,
            'visites' => $visites,
            // 'idanimal' => $idanimal,

        ]);
    }

    #[Route('/{id}/edit', name: 'carnet_sante_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, CarnetSante $carnetSante): Response
    {
        $form = $this->createForm(CarnetSanteType::class, $carnetSante);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('carnet_sante_index');
        }

        return $this->render('carnet_sante/edit.html.twig', [
            'carnet_sante' => $carnetSante,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'carnet_sante_delete', methods: ['POST'])]
    public function delete(Request $request, CarnetSante $carnetSante): Response
    {
        if ($this->isCsrfTokenValid('delete' . $carnetSante->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($carnetSante);
            $entityManager->flush();
        }

        return $this->redirectToRoute('carnet_sante_index');
    }
}

templates/carnet_sante/_delete_form.html.twig
<form method="post" action="{{ path('carnet_sante_delete', {'id': carnet_sante.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
  <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ carnet_sante.id) }}">
  <button class="btn btn-danger">Supprimer</button>
</form>

templates/carnet_sante/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/carnet_sante/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editer CarnetSante{% endblock %}

{% block body %}
    <h1>Editer un carnet de santé</h1>

    {{ include('carnet_sante/_form.html.twig', {'button_label': 'Modifier'}) }}

    <a class="btn btn-secondary" href="{{ path('carnet_sante_index') }}">Revenir à la liste</a>

    {{ include('carnet_sante/_delete_form.html.twig') }}
{% endblock %}

templates/carnet_sante/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Carnet Sante index
{% endblock %}

{% block body %}

    {%  if is_granted("ROLE_ADMIN") %} 
        <h1>Les Carnets de Santé :</h1>
        <br>

        <div class="table-responsive ">
            <table  class="table table-striped table-primary">
                <thead class="table-dark">
                    <tr>
                        <th>Prenom</th>
                        <th>Maitre</th>
                        <th>Voir</th>
                        {# <th>Editer</th> #}
                    </tr>
                </thead>
                <tbody>
                {% for carnet_sante in carnet_santes %}
                    <tr>
                            <td class="fw-bold">{{ carnet_sante.animal.prenom}}</td>
                            <td>{{ carnet_sante.animal.membre.pseudo}}</td>
                            <td>
                                <a href="{{ path('carnet_sante_show', {'id': carnet_sante.id}) }}"><i class="far fa-eye"></i></a>
                            </td>
                            {# <td>
                                <a href="{{ path('carnet_sante_edit', {'id': carnet_sante.id}) }}"><i class="far fa-edit"></i></a>
                            </td> #}
                        </tr>
                 {% else %}
                    <tr>
                        <td colspan="2">Aucun carnet</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

    {% elseif is_granted("ROLE_ABONNE") %}
        {% if app.user.carnetSantes is not empty  %}
            <h1>Vos carnets de santé</h1>

                <div class="table-responsive ">
                    <table class="table table-striped table-primary">
                        <thead class="table-dark">
                            <tr>
                                <th>Prenom</th>
                                <th>Propriétaire</th>
                                <th>Voir</th>
                                {# <th>Editer</th> #}
                            </tr>
                        </thead>
                        <tbody>
                                    {% for carnet_sante in app.user.carnetSantes %}     
                            <tr>
                                    <td class="fw-bold">{{ carnet_sante.animal.prenom}}</td>
                                    <td>{{ carnet_sante.animal.membre.pseudo}}</td>
                                    <td>
                                        <a href="{{ path('carnet_sante_show', {'id': carnet_sante.id}) }}"><i class="far fa-eye"></i></a>
                                    </td>
                                    {# <td>
                                        <a href="{{ path('carnet_sante_edit', {'id': carnet_sante.id}) }}"><i class="far fa-edit"></i></a>
                                    </td> #}
                            </tr>
                                    {% else %}
                            <tr>
                                <td colspan="2">Pas d'animaux enregistrés</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                                {% endfor %}
        {% else %}
        <p>Pas encore d'animaux enrengistrés, mais quel dommage vous avez droit à un accès à nos carnets de santé en ligne pour vos monstres</p>
        {% endif %}
        
    {% endif %}
    
{% endblock %}

templates/carnet_sante/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau Carnet de Santé{% endblock %}

{% block body %}
    <h1>Créer un nouveau carnet de santé</h1>

    {{ include('carnet_sante/_form.html.twig') }}

    <a class="btn btn-secondary" href="{{ path('carnet_sante_index') }}">Revenir à la liste</a>
{% endblock %}

templates/carnet_sante/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}CarnetSante
{% endblock %}

{% block body %}
	<div id="carnet" class="row">
		<div id="card-title">
			<h1 class="text-center">E-Carnet
			</div>
		</h1>

		<div class="col-lg-6" id="id">
			<div>
				<div id="card-id">
					<div id="card-number">
						<p class="cardtitle">Carte nationale d'identité (id) :
						</p>
						<p>{{carnet_sante.animal.id}}</p>
					</div>
					<p class="cardtitle">Espèce :
					</p>
					<p>{{carnet_sante.animal.espece}}</p>
				</div>
				<div id="card-information">
					<div id="card-photo">
						{% for image in carnet_sante.animal.images %}
							<img src="{{ asset('/uploads/animal_photo/'~ image.name) }}" alt="photo de notre bete" width="146" height="146">
						{% endfor %}
					</div>
					<div id="card-text">
						<div id="card-name">
							<div class="card-box"></div>
							<p class="cardtitle">Prénom :</p>
							<p>{{carnet_sante.animal.prenom}}</p>
							<div class="card-box"></div>
							<p class="cardtitle">Couleur :</p>
							<p>{{carnet_sante.animal.couleur}}</p>
						</div>
						<div id="card-detail">
							<div class="card-box">
								<p class="cardtitle">Sexe :</p>
								<p>{{carnet_sante.animal.sexe}}</p>
							</div>
							<div class="card-box">
								<p class="cardtitle">Age :</p>
								<p>{{carnet_sante.animal.age}}</p>
							</div>
							<div class="card-box">
								<p class="cardtitle">Description :</p>
								<p>{{carnet_sante.animal.description}}</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="col-lg-6 table-responsive align-bottom" id="operation">
			<h2 class="h4 text-center">Mes opérations
			</h2>
			<table class=" table caption-top">
				<thead>
					<tr>
						<th>Date</th>
						<th>Nom</th>
						<th>Symptômes</th>
						<th>Analyses</th>
						<th>Specialiste</th>
					</tr>
				</thead>
				<tbody>
					{% for visite in visites %}
						{% if visite.action == "operation" %}
							<tr>
								<td>{{visite.dateVisite ? visite.dateVisite|date('d/m/y') : '' }}</td>
								<td>{{visite.nom}}</td>
								<td>{{ visite.Symptômes }}</td>
								<td>{{ visite.analyses }}</td>
								{% if visite.specialiste.name is defined %}
									<td>{{ visite.specialiste.nom }}</td>
								{% else %}
									<td>
										<i class="fas fa-times"></i>
									</td>
								{% endif %}
							</tr>
						{% endif %}
					{% endfor %}
				</tbody>
			</table>

		</div>

		<article class="col-lg-6 table-responsive align-bottom" id="visite">
			<h2 class="h4 text-center">Mes Visites vétérinaires
			</h2>
			<table class=" table caption-top">
				<thead>
					<tr>
						<th scope="col">Date de la visite</th>
						<th scope="col">Symptômes</th>
						<th scope="col">Diagnostique</th>
						<th scope="col">Specialiste</th>
					</tr>
				</thead>
				<tbody>
					{% for visite in visites %}
						{% if visite.action == "visite_medical" %}
							<tr>
								<td>{{visite.dateVisite ? visite.dateVisite|date('d/m/y') : '' }}</td>
								<td>{{ visite.Symptômes }}</td>
								<td>{{ visite.diagnostique }}</td>
								{% if visite.specialiste.name is defined %}
									<td>{{ visite.specialiste.nom }}</td>
								{% else %}
									<td>
										<i class="fas fa-times"></i>
									</td>
								{% endif %}
							</tr>
						{% endif %}
					{% endfor %}
				</tbody>
			</table>
		</article>

		<article class="col-lg-6 table-responsive align-bottom" id="vaccination">
			<h2 class="h4 text-center">Mes Vaccinations
			</h2>
			<table class=" table caption-top">
				<thead>
					<tr>
						<th scope="col">Date</th>
						<th>Nom</th>
						<th scope="col">Diagnostique</th>
						<th scope="col">Specialiste</th>
					</tr>
				</thead>
				<tbody>
					{% for visite in visites %}
						{% if visite.action == "vaccimation" %}
							<tr>
								<td>{{visite.dateVisite ? visite.dateVisite|date('d/m/y') : '' }}</td>
								<td>{{visite.nom}}</td>
								<td>{{ visite.diagnostique }}</td>
								{% if visite.specialiste.name is defined %}
									<td>{{ visite.specialiste.nom }}</td>
								{% else %}
									<td>
										<i class="fas fa-times"></i>
									</td>
								{% endif %}
							</tr>
						{% endif %}
					{% endfor %}
				</tbody>
			</table>
		</article>

		<a class="btn btn-outline-primary" href="{{ path('visite_medical_new', {'id': carnet_sante.id }) }}">Ajouter</a>
	</div>

	{% if is_granted("ROLE_ADMIN") %}
		<div id="b-carnet" class="d-grid gap-2 col-3">

			<button type="button" class="btn btn-primary">
				<a href="{{ path('carnet_sante_index') }}">Retour à la liste</a>
			</button>
			<button class="btn btn-primary">
				<a href="{{ path('carnet_sante_edit', {'id': carnet_sante.id}) }}">Éditer le carnet</a>
			</button>
			{{ include('carnet_sante/_delete_form.html.twig') }}

		</div>
	{% else %}
		<div id="b-carnet" class="d-grid gap-2 col-3">
			<button type="button" class="btn btn-primary">
				<a href="{{ path('animal_index') }}">Mes animaux</a>
			</button>
		</div>

	{% endif %}

{% endblock %}