src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\component\HttpFoundation\File\File;

/**
 * @ORM\Entity(repositoryClass=ProduitRepository::class)
 * @Vich\Uploadable
 */
class Produit
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $reference;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo;

    /**
     * @Vich\UploadableField(mapping="photo_images", fileNameProperty="photo")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $origine_site;

    /**
     * @ORM\ManyToOne(targetEntity=Categories::class, inversedBy="produit")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categories;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReference(): ?int
    {
        return $this->reference;
    }

    public function setReference(int $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function setImageFile(File $photo = null)
    {
        $this->imageFile = $photo;
        if ($photo) {
            $this->createdAt = new \DateTime('now');
        }
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getOrigineSite(): ?string
    {
        return $this->origine_site;
    }

    public function setOrigineSite(?string $origine_site): self
    {
        $this->origine_site = $origine_site;

        return $this;
    }

    public function getCategories(): ?Categories
    {
        return $this->categories;
    }

    public function setCategories(?Categories $categories): self
    {
        $this->categories = $categories;

        return $this;
    }
}

src/Form/ProduitType.php
<?php

namespace App\Form;

use App\Entity\Categories;
use App\Entity\Produit;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\Positive;

class ProduitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('reference', NumberType::class, [
                'constraints' => [
                    new Positive([
                        "message" => "Le chiffre doit être positif",
                    ]),
                    new Length([
                        'min' => 1,
                        'minMessage' => 'Renseignez un prix supérieur à 1',
                    ]),
                ]
            ])
            ->add('titre')
            ->add('categories', EntityType::class, [
                "class" => Categories::class,
                "choice_label" => "name",
                "label" => "Catégorie",
                'required' => true
            ])
            ->add('description')
            ->add('photo', FileType::class, [
                'required' => true,
                'mapped' => false
            ])

            ->add('prix', NumberType::class, [
                'constraints' => [
                    new Positive([
                        "message" => "Le chiffre doit être positif",
                    ]),
                    new Length([
                        'min' => 1,
                        'minMessage' => 'Renseignez un prix supérieur à 1',
                    ]),
                ]
            ])
            ->add('origine_site');
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Produit::class,
        ]);
    }
}

src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Form\ProduitType;
use App\Repository\ProduitRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/produit')]
class ProduitController extends AbstractController
{
    #[Route('/', name: 'produit_index', methods: ['GET'])]
    public function index(ProduitRepository $produitRepository): Response
    {
        return $this->render('produit/index.html.twig', [
            'produits' => $produitRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'produit_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ProduitRepository $pr): Response
    {

        $produit = new Produit();
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // On récupère les images transmis
            $image = $form->get('photo')->getData();

            // Generée un nom aleatoire pour l'image
            $fichier = md5(uniqid()) . '.' . $image->guessExtension();


            // On copie le fichier dans le dossier uploads
            $image->move(
                $this->getParameter('photo_images'),
                $fichier
            );
            $produit->setPhoto($fichier);


            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($produit);
            $entityManager->flush();

            return $this->redirectToRoute('produit_index');
        }

        return $this->render('produit/new.html.twig', [
            'produit' => $produit,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'produit_show', methods: ['GET'])]
    public function show(Produit $produit): Response
    {
        return $this->render('produit/show.html.twig', [
            'produit' => $produit,
        ]);
    }

    #[Route('/{id}/edit', name: 'produit_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Produit $produit): Response
    {
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('produit_index');
        }

        return $this->render('produit/edit.html.twig', [
            'produit' => $produit,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'produit_delete', methods: ['POST'])]
    public function delete(Request $request, Produit $produit): Response
    {
        if ($this->isCsrfTokenValid('delete' . $produit->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($produit);
            $entityManager->flush();
        }

        return $this->redirectToRoute('produit_index');
    }
}

templates/produit/_delete_form.html.twig
<form method="post" action="{{ path('produit_delete', {'id': produit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
    <button class="btn btn-danger mx-2">Supprimer</button>
</form>

templates/produit/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary mt-2">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/produit/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editer Produit{% endblock %}

{% block body %}
    <h1>Modifier un Produit</h1>

    {{ include('produit/_form.html.twig', {'button_label': 'Modifier'}) }}
    <div class="d-flex my-2">
        <a class="btn btn-secondary" href="{{ path('produit_index') }}">Revenir à la liste</a>

        {{ include('produit/_delete_form.html.twig') }}
    </div>

    
{% endblock %}

templates/produit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produits
{% endblock %}

{% block body %}
	<h1>Les produits :</h1>
<br>
	<table class="table table-striped table-primary table-responsive">
		<thead class="table-dark">
			<tr>
				<th>Référence</th>
				<th>Titre</th>
				<th>Catégorie</th>
				<th>Description</th>
				<th>Photo</th>
				<th>Prix</th>
				<th>Origine_site</th>
				<th>Voir</th>
				<th>Editer</th>
			</tr>
		</thead>
		<tbody>
			{% for produit in produits %}
				<tr>
					<td class="fw-bold">{{ produit.reference }}</td>
					<td class="fw-bold">{{ produit.titre }}</td>
					<td>{{ produit.categories.name }}</td>
					<td>{{ produit.description }}</td>
					<td>{{ produit.photo }}</td>
					<td>{{ produit.prix }}</td>
					<td>{{ produit.origineSite }}</td>
					<td>
						<a href="{{ path('produit_show', {'id': produit.id}) }}"><i class="far fa-eye"></i></a>
					</td>
					<td>
						<a href="{{ path('produit_edit', {'id': produit.id}) }}"><i class="far fa-edit"></i></a>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="9">Aucun produit enregistré</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
 	
		<a class="btn btn-primary" href="{{ path('produit_new') }}">Nouveau produit</a>

{% endblock %}

templates/produit/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau produit{% endblock %}

{% block body %}
    <h1>Créer un nouveau produit</h1>

    {{ include('produit/_form.html.twig') }}

    <a class="btn btn-secondary" href="{{ path('produit_index') }}">Revenir à la liste</a>
{% endblock %}

templates/produit/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit{% endblock %}

{% block body %}
    <h1>Produit</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ produit.id }}</td>
            </tr>
            <tr>
                <th>Référence</th>
                <td>{{ produit.reference }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ produit.titre }}</td>
            </tr>
            <tr>
                <th>Catégorie</th>
                <td>{{ produit.categories.name }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ produit.description }}</td>
            </tr>
            <tr>
                <th>Photo</th>
                <td>{{ produit.photo }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ produit.prix }}</td>
            </tr>
            <tr>
                <th>Origine_site</th>
                <td>{{ produit.origineSite }}</td>
            </tr>
        </tbody>
    </table>
    <div class="mb-2">
        <a class="btn btn-primary" href="{{ path('produit_edit', {'id': produit.id}) }}">Modifier</a>

        <a class="btn btn-secondary" href="{{ path('produit_index') }}">Revenir à la liste</a>
    </div>
    

    {{ include('produit/_delete_form.html.twig') }}
{% endblock %}